services:
  electrs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ELECTRS_VERSION: ${ELECTRS_VERSION:-v0.11.1}
    image: lightningos/electrs:${ELECTRS_VERSION:-v0.11.1}
    container_name: electrs
    restart: unless-stopped
    stop_grace_period: 1m
    user: "1000:1000"
    networks:
      - default
      - bitcoincore
    ports:
      - "127.0.0.1:50001:50001"
      - "127.0.0.1:4224:4224"
    volumes:
      - /data/electrs:/data/db
    command:
      - --network=bitcoin
      - --db-dir=/data/db
      - --daemon-rpc-addr=bitcoind:8332
      - --daemon-p2p-addr=bitcoind:8333
      - --electrum-rpc-addr=0.0.0.0:50001
      - --monitoring-addr=0.0.0.0:4224
      - --cookie=${BITCOIN_RPC_USER}:${BITCOIN_RPC_PASS}
      - --index-batch-size=10
      - --log-filters=INFO

networks:
  default:
    name: electrs_default
  bitcoincore:
    external: true
    name: bitcoincore_default
